<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Country;
use App\Models\State;
use App\Models\City;

class ColombiaLocationSeeder extends Seeder
{
    public function run(): void
    {

        $colombia = Country::firstOrCreate(['name' => 'Colombia',
                                            'code' => 'CO',
                                            'phone_code' => '+57',
                                            'currency' => 'COP',
                                            'language' => 'es',
                                            'region' => 'América del Sur',
                                            ]); 

        // === Estados/Departamentos ===
        $amazonas = State::firstOrCreate(['name' => 'Amazonas', 'country_id' => $colombia->id]);
        $antioquia = State::firstOrCreate(['name' => 'Antioquia', 'country_id' => $colombia->id]);
        $arauca = State::firstOrCreate(['name' => 'Arauca', 'country_id' => $colombia->id]);
        $atlantico = State::firstOrCreate(['name' => 'Atlántico', 'country_id' => $colombia->id]);
        $bolivar = State::firstOrCreate(['name' => 'Bolívar', 'country_id' => $colombia->id]);
        $boyaca = State::firstOrCreate(['name' => 'Boyacá', 'country_id' => $colombia->id]);
        $caldas = State::firstOrCreate(['name' => 'Caldas', 'country_id' => $colombia->id]);
        $caqueta = State::firstOrCreate(['name' => 'Caquetá', 'country_id' => $colombia->id]);
        $casanare = State::firstOrCreate(['name' => 'Casanare', 'country_id' => $colombia->id]);
        $cauca = State::firstOrCreate(['name' => 'Cauca', 'country_id' => $colombia->id]);
        $cesar = State::firstOrCreate(['name' => 'Cesar', 'country_id' => $colombia->id]);
        $choco = State::firstOrCreate(['name' => 'Chocó', 'country_id' => $colombia->id]);
        $cordoba = State::firstOrCreate(['name' => 'Córdoba', 'country_id' => $colombia->id]);
        $cundinamarca = State::firstOrCreate(['name' => 'Cundinamarca', 'country_id' => $colombia->id]);
        $guainia = State::firstOrCreate(['name' => 'Guainía', 'country_id' => $colombia->id]);
        $guaviare = State::firstOrCreate(['name' => 'Guaviare', 'country_id' => $colombia->id]);
        $huila = State::firstOrCreate(['name' => 'Huila', 'country_id' => $colombia->id]);
        $guajira = State::firstOrCreate(['name' => 'La Guajira', 'country_id' => $colombia->id]);
        $magdalena = State::firstOrCreate(['name' => 'Magdalena', 'country_id' => $colombia->id]);
        $meta = State::firstOrCreate(['name' => 'Meta', 'country_id' => $colombia->id]);
        $narino = State::firstOrCreate(['name' => 'Nariño', 'country_id' => $colombia->id]);
        $nortesantander = State::firstOrCreate(['name' => 'Norte de Santander', 'country_id' => $colombia->id]);
        $putumayo = State::firstOrCreate(['name' => 'Putumayo', 'country_id' => $colombia->id]);
        $quindio = State::firstOrCreate(['name' => 'Quindío', 'country_id' => $colombia->id]);
        $risaralda = State::firstOrCreate(['name' => 'Risaralda', 'country_id' => $colombia->id]);
        $sanandres = State::firstOrCreate(['name' => 'San Andrés y Providencia', 'country_id' => $colombia->id]);
        $santander = State::firstOrCreate(['name' => 'Santander', 'country_id' => $colombia->id]);
        $sucre = State::firstOrCreate(['name' => 'Sucre', 'country_id' => $colombia->id]);
        $tolima = State::firstOrCreate(['name' => 'Tolima', 'country_id' => $colombia->id]);
        $valle = State::firstOrCreate(['name' => 'Valle del Cauca', 'country_id' => $colombia->id]);
        $vaupes = State::firstOrCreate(['name' => 'Vaupés', 'country_id' => $colombia->id]);
        $vichada = State::firstOrCreate(['name' => 'Vichada', 'country_id' => $colombia->id]);

        // === Ciudades ===
        City::insert([
            //Amazonas
            ['name' => 'Leticia', 'state_id' => $amazonas->id],
            ['name' => 'Puerto Nariño', 'state_id' => $amazonas->id],

            // Antioquia
            ['name' => 'Abejorral', 'state_id' => $antioquia->id],
            ['name' => 'Abriaquí', 'state_id' => $antioquia->id],
            ['name' => 'Alejandría', 'state_id' => $antioquia->id],
            ['name' => 'Amagá', 'state_id' => $antioquia->id],
            ['name' => 'Amalfi', 'state_id' => $antioquia->id],
            ['name' => 'Andes', 'state_id' => $antioquia->id],
            ['name' => 'Angelópolis', 'state_id' => $antioquia->id],
            ['name' => 'Angostura', 'state_id' => $antioquia->id],
            ['name' => 'Anorí', 'state_id' => $antioquia->id],
            ['name' => 'Anzá', 'state_id' => $antioquia->id],
            ['name' => 'Apartadó', 'state_id' => $antioquia->id],
            ['name' => 'Arboletes', 'state_id' => $antioquia->id],
            ['name' => 'Argelia', 'state_id' => $antioquia->id],
            ['name' => 'Armenia', 'state_id' => $antioquia->id],
            ['name' => 'Barbosa', 'state_id' => $antioquia->id],
            ['name' => 'Bello', 'state_id' => $antioquia->id],
            ['name' => 'Belmira', 'state_id' => $antioquia->id],
            ['name' => 'Betania', 'state_id' => $antioquia->id],
            ['name' => 'Betulia', 'state_id' => $antioquia->id],
            ['name' => 'Blandón', 'state_id' => $antioquia->id], // si aplica
            ['name' => 'Briceño', 'state_id' => $antioquia->id],
            ['name' => 'Buriticá', 'state_id' => $antioquia->id],
            ['name' => 'Cáceres', 'state_id' => $antioquia->id],
            ['name' => 'Caicedo', 'state_id' => $antioquia->id],
            ['name' => 'Caldas', 'state_id' => $antioquia->id],
            ['name' => 'Campamento', 'state_id' => $antioquia->id],
            ['name' => 'Cañasgordas', 'state_id' => $antioquia->id],
            ['name' => 'Caracolí', 'state_id' => $antioquia->id],
            ['name' => 'Caramanta', 'state_id' => $antioquia->id],
            ['name' => 'Carepa', 'state_id' => $antioquia->id],
            ['name' => 'Carolina del Príncipe', 'state_id' => $antioquia->id],
            ['name' => 'Caucasia', 'state_id' => $antioquia->id],
            ['name' => 'Chigorodó', 'state_id' => $antioquia->id],
            ['name' => 'Cisneros', 'state_id' => $antioquia->id],
            ['name' => 'Cocorná', 'state_id' => $antioquia->id],
            ['name' => 'Concepción', 'state_id' => $antioquia->id],
            ['name' => 'Concordia', 'state_id' => $antioquia->id],
            ['name' => 'Copacabana', 'state_id' => $antioquia->id],
            ['name' => 'Dabeiba', 'state_id' => $antioquia->id],
            ['name' => 'Don Matías', 'state_id' => $antioquia->id],
            ['name' => 'Ebéjico', 'state_id' => $antioquia->id],
            ['name' => 'El Bagre', 'state_id' => $antioquia->id],
            ['name' => 'El Carmen de Viboral', 'state_id' => $antioquia->id],
            ['name' => 'Entrerríos', 'state_id' => $antioquia->id],
            ['name' => 'Envigado', 'state_id' => $antioquia->id],
            ['name' => 'Fredonia', 'state_id' => $antioquia->id],
            ['name' => 'Frontino', 'state_id' => $antioquia->id],
            ['name' => 'Giraldo', 'state_id' => $antioquia->id],
            ['name' => 'Girardota', 'state_id' => $antioquia->id],
            ['name' => 'Gómez Plata', 'state_id' => $antioquia->id],
            ['name' => 'Granada', 'state_id' => $antioquia->id],
            ['name' => 'Guadalupe', 'state_id' => $antioquia->id],
            ['name' => 'Guarne', 'state_id' => $antioquia->id],
            ['name' => 'Guatapé', 'state_id' => $antioquia->id],
            ['name' => 'Heliconia', 'state_id' => $antioquia->id],
            ['name' => 'Hispania', 'state_id' => $antioquia->id],
            ['name' => 'Itagüí', 'state_id' => $antioquia->id],
            ['name' => 'Ituango', 'state_id' => $antioquia->id],
            ['name' => 'Jardín', 'state_id' => $antioquia->id],
            ['name' => 'Jericó', 'state_id' => $antioquia->id],
            ['name' => 'La Ceja', 'state_id' => $antioquia->id],
            ['name' => 'La Estrella', 'state_id' => $antioquia->id],
            ['name' => 'La Pintada', 'state_id' => $antioquia->id],
            ['name' => 'La Unión', 'state_id' => $antioquia->id],
            ['name' => 'Liborina', 'state_id' => $antioquia->id],
            ['name' => 'Maceo', 'state_id' => $antioquia->id],
            ['name' => 'Marinilla', 'state_id' => $antioquia->id],
            ['name' => 'Medellín', 'state_id' => $antioquia->id],
            ['name' => 'Montebello', 'state_id' => $antioquia->id],
            ['name' => 'Murindó', 'state_id' => $antioquia->id],
            ['name' => 'Mutatá', 'state_id' => $antioquia->id],
            ['name' => 'Nariño', 'state_id' => $antioquia->id],
            ['name' => 'Nechí', 'state_id' => $antioquia->id],
            ['name' => 'Necoclí', 'state_id' => $antioquia->id],
            ['name' => 'Olaya', 'state_id' => $antioquia->id],
            ['name' => 'Peñol', 'state_id' => $antioquia->id],
            ['name' => 'Peque', 'state_id' => $antioquia->id],
            ['name' => 'Pueblorrico', 'state_id' => $antioquia->id],
            ['name' => 'Puerto Berrío', 'state_id' => $antioquia->id],
            ['name' => 'Puerto Nare', 'state_id' => $antioquia->id],
            ['name' => 'Puerto Triunfo', 'state_id' => $antioquia->id],
            ['name' => 'Remedios', 'state_id' => $antioquia->id],
            ['name' => 'Retiro', 'state_id' => $antioquia->id],
            ['name' => 'Rionegro', 'state_id' => $antioquia->id],
            ['name' => 'Sabanalarga', 'state_id' => $antioquia->id],
            ['name' => 'Sabaneta', 'state_id' => $antioquia->id],
            ['name' => 'Salgar', 'state_id' => $antioquia->id],
            ['name' => 'San Andrés de Cuerquia', 'state_id' => $antioquia->id],
            ['name' => 'San Carlos', 'state_id' => $antioquia->id],
            ['name' => 'San Francisco', 'state_id' => $antioquia->id],
            ['name' => 'San Jerónimo', 'state_id' => $antioquia->id],
            ['name' => 'San José de la Montaña', 'state_id' => $antioquia->id],
            ['name' => 'San Juan de Urabá', 'state_id' => $antioquia->id],
            ['name' => 'San Luis', 'state_id' => $antioquia->id],
            ['name' => 'San Pedro', 'state_id' => $antioquia->id],
            ['name' => 'San Pedro de Urabá', 'state_id' => $antioquia->id],
            ['name' => 'San Rafael', 'state_id' => $antioquia->id],
            ['name' => 'San Roque', 'state_id' => $antioquia->id],
            ['name' => 'San Vicente', 'state_id' => $antioquia->id],
            ['name' => 'Santa Bárbara', 'state_id' => $antioquia->id],
            ['name' => 'Santa Fe de Antioquia', 'state_id' => $antioquia->id],
            ['name' => 'Santa Rosa de Osos', 'state_id' => $antioquia->id],
            ['name' => 'Santo Domingo', 'state_id' => $antioquia->id],
            ['name' => 'Segovia', 'state_id' => $antioquia->id],
            ['name' => 'Sonsón', 'state_id' => $antioquia->id],
            ['name' => 'Sopetrán', 'state_id' => $antioquia->id],
            ['name' => 'Támesis', 'state_id' => $antioquia->id],
            ['name' => 'Tarazá', 'state_id' => $antioquia->id],
            ['name' => 'Tarso', 'state_id' => $antioquia->id],
            ['name' => 'Titiribí', 'state_id' => $antioquia->id],
            ['name' => 'Toledo', 'state_id' => $antioquia->id],
            ['name' => 'Turbo', 'state_id' => $antioquia->id],
            ['name' => 'Uramita', 'state_id' => $antioquia->id],
            ['name' => 'Urrao', 'state_id' => $antioquia->id],
            ['name' => 'Valdivia', 'state_id' => $antioquia->id],
            ['name' => 'Valparaíso', 'state_id' => $antioquia->id],
            ['name' => 'Vegachí', 'state_id' => $antioquia->id],
            ['name' => 'Venecia', 'state_id' => $antioquia->id],
            ['name' => 'Vigía del Fuerte', 'state_id' => $antioquia->id],
            ['name' => 'Yalí', 'state_id' => $antioquia->id],
            ['name' => 'Yarumal', 'state_id' => $antioquia->id],
            ['name' => 'Yolombó', 'state_id' => $antioquia->id],
            ['name' => 'Yondó', 'state_id' => $antioquia->id],
            ['name' => 'Zaragoza', 'state_id' => $antioquia->id],

            //arauca
            ['name' => 'Arauca', 'state_id' => $arauca->id],
            ['name' => 'Arauquita', 'state_id' => $arauca->id],
            ['name' => 'Cravo Norte', 'state_id' => $arauca->id],
            ['name' => 'Fortul', 'state_id' => $arauca->id],
            ['name' => 'Puerto Rondón', 'state_id' => $arauca->id],
            ['name' => 'Saravena', 'state_id' => $arauca->id],
            ['name' => 'Tame', 'state_id' => $arauca->id],
            
            // Atlántico
            ['name' => 'Baranoa', 'state_id' => $atlantico->id],
            ['name' => 'Barranquilla', 'state_id' => $atlantico->id],
            ['name' => 'Campo de la Cruz', 'state_id' => $atlantico->id],
            ['name' => 'Candelaria', 'state_id' => $atlantico->id],
            ['name' => 'Galapa', 'state_id' => $atlantico->id],
            ['name' => 'Juan de Acosta', 'state_id' => $atlantico->id],
            ['name' => 'Luruaco', 'state_id' => $atlantico->id],
            ['name' => 'Malambo', 'state_id' => $atlantico->id],
            ['name' => 'Manatí', 'state_id' => $atlantico->id],
            ['name' => 'Palmar de Varela', 'state_id' => $atlantico->id],
            ['name' => 'Piojó', 'state_id' => $atlantico->id],
            ['name' => 'Polonuevo', 'state_id' => $atlantico->id],
            ['name' => 'Ponedera', 'state_id' => $atlantico->id],
            ['name' => 'Puerto Colombia', 'state_id' => $atlantico->id],
            ['name' => 'Repelón', 'state_id' => $atlantico->id],
            ['name' => 'Sabanagrande', 'state_id' => $atlantico->id],
            ['name' => 'Sabanalarga', 'state_id' => $atlantico->id],
            ['name' => 'Santa Lucía', 'state_id' => $atlantico->id],
            ['name' => 'Santo Tomás', 'state_id' => $atlantico->id],
            ['name' => 'Soledad', 'state_id' => $atlantico->id],
            ['name' => 'Suán', 'state_id' => $atlantico->id],
            ['name' => 'Tubará', 'state_id' => $atlantico->id],
            ['name' => 'Usiacurí', 'state_id' => $atlantico->id],
            
            //Bolivar
            ['name' => 'Achí', 'state_id' => $bolivar->id],
            ['name' => 'Altos del Rosario', 'state_id' => $bolivar->id],
            ['name' => 'Arenal', 'state_id' => $bolivar->id],
            ['name' => 'Arjona', 'state_id' => $bolivar->id],
            ['name' => 'Arroyohondo', 'state_id' => $bolivar->id],
            ['name' => 'Barranco de Loba', 'state_id' => $bolivar->id],
            ['name' => 'Calamar', 'state_id' => $bolivar->id],
            ['name' => 'Cantagallo', 'state_id' => $bolivar->id],
            ['name' => 'Cicuco', 'state_id' => $bolivar->id],
            ['name' => 'Clemencia', 'state_id' => $bolivar->id],
            ['name' => 'Córdoba', 'state_id' => $bolivar->id],
            ['name' => 'Cartagena de Indias', 'state_id' => $bolivar->id],
            ['name' => 'El Carmen de Bolívar', 'state_id' => $bolivar->id],
            ['name' => 'El Guamo', 'state_id' => $bolivar->id],
            ['name' => 'El Peñón', 'state_id' => $bolivar->id],
            ['name' => 'Hatillo de Loba', 'state_id' => $bolivar->id],
            ['name' => 'Magangué', 'state_id' => $bolivar->id],
            ['name' => 'Mahates', 'state_id' => $bolivar->id],
            ['name' => 'Margarita', 'state_id' => $bolivar->id],
            ['name' => 'María La Baja', 'state_id' => $bolivar->id],
            ['name' => 'Montecristo', 'state_id' => $bolivar->id],
            ['name' => 'Morales', 'state_id' => $bolivar->id],
            ['name' => 'Norosí', 'state_id' => $bolivar->id],
            ['name' => 'Pinillos', 'state_id' => $bolivar->id],
            ['name' => 'Regidor', 'state_id' => $bolivar->id],
            ['name' => 'Río Viejo', 'state_id' => $bolivar->id],
            ['name' => 'San Cristóbal', 'state_id' => $bolivar->id],
            ['name' => 'San Estanislao', 'state_id' => $bolivar->id],
            ['name' => 'San Fernando', 'state_id' => $bolivar->id],
            ['name' => 'San Jacinto', 'state_id' => $bolivar->id],
            ['name' => 'San Jacinto del Cauca', 'state_id' => $bolivar->id],
            ['name' => 'San Juan Nepomuceno', 'state_id' => $bolivar->id],
            ['name' => 'San Martín de Loba', 'state_id' => $bolivar->id],
            ['name' => 'San Pablo', 'state_id' => $bolivar->id],
            ['name' => 'Santa Catalina', 'state_id' => $bolivar->id],
            ['name' => 'Santa Cruz de Mompox', 'state_id' => $bolivar->id],
            ['name' => 'Santa Rosa', 'state_id' => $bolivar->id],
            ['name' => 'Santa Rosa del Sur', 'state_id' => $bolivar->id],
            ['name' => 'Simití', 'state_id' => $bolivar->id],
            ['name' => 'Soplaviento', 'state_id' => $bolivar->id],
            ['name' => 'Talaigua Nuevo', 'state_id' => $bolivar->id],
            ['name' => 'Tiquisio', 'state_id' => $bolivar->id],
            ['name' => 'Turbaco', 'state_id' => $bolivar->id],
            ['name' => 'Turbaná', 'state_id' => $bolivar->id],
            ['name' => 'Villanueva', 'state_id' => $bolivar->id],
            ['name' => 'Zambrano', 'state_id' => $bolivar->id],

            //Boyaca
            ['name' => 'Almeida', 'state_id' => $boyaca->id],
            ['name' => 'Aquitania', 'state_id' => $boyaca->id],
            ['name' => 'Arcabuco', 'state_id' => $boyaca->id],
            ['name' => 'Belén', 'state_id' => $boyaca->id],
            ['name' => 'Berbeo', 'state_id' => $boyaca->id],
            ['name' => 'Betéitiva', 'state_id' => $boyaca->id],
            ['name' => 'Boavita', 'state_id' => $boyaca->id],
            ['name' => 'Boyacá', 'state_id' => $boyaca->id],
            ['name' => 'Briceño', 'state_id' => $boyaca->id],
            ['name' => 'Buenavista', 'state_id' => $boyaca->id],
            ['name' => 'Busbanzá', 'state_id' => $boyaca->id],
            ['name' => 'Caldas', 'state_id' => $boyaca->id],
            ['name' => 'Campohermoso', 'state_id' => $boyaca->id],
            ['name' => 'Cerinza', 'state_id' => $boyaca->id],
            ['name' => 'Chinavita', 'state_id' => $boyaca->id],
            ['name' => 'Chiquinquirá', 'state_id' => $boyaca->id],
            ['name' => 'Chíquiza', 'state_id' => $boyaca->id],
            ['name' => 'Chiscas', 'state_id' => $boyaca->id],
            ['name' => 'Chita', 'state_id' => $boyaca->id],
            ['name' => 'Chitaraque', 'state_id' => $boyaca->id],
            ['name' => 'Chivatá', 'state_id' => $boyaca->id],
            ['name' => 'Chivor', 'state_id' => $boyaca->id],
            ['name' => 'Ciénega', 'state_id' => $boyaca->id],
            ['name' => 'Cómbita', 'state_id' => $boyaca->id],
            ['name' => 'Coper', 'state_id' => $boyaca->id],
            ['name' => 'Corrales', 'state_id' => $boyaca->id],
            ['name' => 'Covarachía', 'state_id' => $boyaca->id],
            ['name' => 'Cubará', 'state_id' => $boyaca->id],
            ['name' => 'Cucaita', 'state_id' => $boyaca->id],
            ['name' => 'Cuítiva', 'state_id' => $boyaca->id],
            ['name' => 'Duitama', 'state_id' => $boyaca->id],
            ['name' => 'El Cocuy', 'state_id' => $boyaca->id],
            ['name' => 'El Espino', 'state_id' => $boyaca->id],
            ['name' => 'Firavitoba', 'state_id' => $boyaca->id],
            ['name' => 'Floresta', 'state_id' => $boyaca->id],
            ['name' => 'Gachantivá', 'state_id' => $boyaca->id],
            ['name' => 'Gámeza', 'state_id' => $boyaca->id],
            ['name' => 'Garagoa', 'state_id' => $boyaca->id],
            ['name' => 'Guacamayas', 'state_id' => $boyaca->id],
            ['name' => 'Guateque', 'state_id' => $boyaca->id],
            ['name' => 'Guayatá', 'state_id' => $boyaca->id],
            ['name' => 'Güicán', 'state_id' => $boyaca->id],
            ['name' => 'Iza', 'state_id' => $boyaca->id],
            ['name' => 'Jenesano', 'state_id' => $boyaca->id],
            ['name' => 'Jericó', 'state_id' => $boyaca->id],
            ['name' => 'Labranzagrande', 'state_id' => $boyaca->id],
            ['name' => 'La Capilla', 'state_id' => $boyaca->id],
            ['name' => 'La Uvita', 'state_id' => $boyaca->id],
            ['name' => 'La Victoria', 'state_id' => $boyaca->id],
            ['name' => 'Macanal', 'state_id' => $boyaca->id],
            ['name' => 'Maripí', 'state_id' => $boyaca->id],
            ['name' => 'Miraflores', 'state_id' => $boyaca->id],
            ['name' => 'Mongua', 'state_id' => $boyaca->id],
            ['name' => 'Monguí', 'state_id' => $boyaca->id],
            ['name' => 'Moniquirá', 'state_id' => $boyaca->id],
            ['name' => 'Motavita', 'state_id' => $boyaca->id],
            ['name' => 'Muzo', 'state_id' => $boyaca->id],
            ['name' => 'Nobsa', 'state_id' => $boyaca->id],
            ['name' => 'Nuevo Colón', 'state_id' => $boyaca->id],
            ['name' => 'Oicatá', 'state_id' => $boyaca->id],
            ['name' => 'Otanche', 'state_id' => $boyaca->id],
            ['name' => 'Pachavita', 'state_id' => $boyaca->id],
            ['name' => 'Páez', 'state_id' => $boyaca->id],
            ['name' => 'Paipa', 'state_id' => $boyaca->id],
            ['name' => 'Pajarito', 'state_id' => $boyaca->id],
            ['name' => 'Panqueba', 'state_id' => $boyaca->id],
            ['name' => 'Pauna', 'state_id' => $boyaca->id],
            ['name' => 'Paya', 'state_id' => $boyaca->id],
            ['name' => 'Paz de Río', 'state_id' => $boyaca->id],
            ['name' => 'Pesca', 'state_id' => $boyaca->id],
            ['name' => 'Pisba', 'state_id' => $boyaca->id],
            ['name' => 'Puerto Boyacá', 'state_id' => $boyaca->id],
            ['name' => 'Quípama', 'state_id' => $boyaca->id],
            ['name' => 'Ramiriquí', 'state_id' => $boyaca->id],
            ['name' => 'Ráquira', 'state_id' => $boyaca->id],
            ['name' => 'Rondón', 'state_id' => $boyaca->id],
            ['name' => 'Saboyá', 'state_id' => $boyaca->id],
            ['name' => 'Sáchica', 'state_id' => $boyaca->id],
            ['name' => 'Samacá', 'state_id' => $boyaca->id],
            ['name' => 'San Eduardo', 'state_id' => $boyaca->id],
            ['name' => 'San José de Pare', 'state_id' => $boyaca->id],
            ['name' => 'San Luis de Gaceno', 'state_id' => $boyaca->id],
            ['name' => 'San Mateo', 'state_id' => $boyaca->id],
            ['name' => 'San Miguel de Sema', 'state_id' => $boyaca->id],
            ['name' => 'San Pablo de Borbur', 'state_id' => $boyaca->id],
            ['name' => 'Santana', 'state_id' => $boyaca->id],
            ['name' => 'Santa María', 'state_id' => $boyaca->id],
            ['name' => 'Santa Rosa de Viterbo', 'state_id' => $boyaca->id],
            ['name' => 'Santa Sofía', 'state_id' => $boyaca->id],
            ['name' => 'Sativanorte', 'state_id' => $boyaca->id],
            ['name' => 'Sativasur', 'state_id' => $boyaca->id],
            ['name' => 'Siachoque', 'state_id' => $boyaca->id],
            ['name' => 'Soatá', 'state_id' => $boyaca->id],
            ['name' => 'Socha', 'state_id' => $boyaca->id],
            ['name' => 'Socotá', 'state_id' => $boyaca->id],
            ['name' => 'Somondoco', 'state_id' => $boyaca->id],
            ['name' => 'Sora', 'state_id' => $boyaca->id],
            ['name' => 'Soracá', 'state_id' => $boyaca->id],
            ['name' => 'Sotaquirá', 'state_id' => $boyaca->id],
            ['name' => 'Susacón', 'state_id' => $boyaca->id],
            ['name' => 'Sutamarchán', 'state_id' => $boyaca->id],
            ['name' => 'Sutatenza', 'state_id' => $boyaca->id],
            ['name' => 'Tasco', 'state_id' => $boyaca->id],
            ['name' => 'Tenza', 'state_id' => $boyaca->id],
            ['name' => 'Tibaná', 'state_id' => $boyaca->id],
            ['name' => 'Tibasosa', 'state_id' => $boyaca->id],
            ['name' => 'Tinjacá', 'state_id' => $boyaca->id],
            ['name' => 'Tipacoque', 'state_id' => $boyaca->id],
            ['name' => 'Toca', 'state_id' => $boyaca->id],
            ['name' => 'Togüí', 'state_id' => $boyaca->id],
            ['name' => 'Tópaga', 'state_id' => $boyaca->id],
            ['name' => 'Tota', 'state_id' => $boyaca->id],
            ['name' => 'Tunja', 'state_id' => $boyaca->id],
            ['name' => 'Tununguá', 'state_id' => $boyaca->id],
            ['name' => 'Turmequé', 'state_id' => $boyaca->id],
            ['name' => 'Tuta', 'state_id' => $boyaca->id],
            ['name' => 'Tutazá', 'state_id' => $boyaca->id],
            ['name' => 'Úmbita', 'state_id' => $boyaca->id],
            ['name' => 'Ventaquemada', 'state_id' => $boyaca->id],
            ['name' => 'Villa de Leyva', 'state_id' => $boyaca->id],
            ['name' => 'Viracachá', 'state_id' => $boyaca->id],
            ['name' => 'Zetaquira', 'state_id' => $boyaca->id],

            //Caldas
            ['name' => 'Manizales', 'state_id' => $caldas->id],
            ['name' => 'Aguadas', 'state_id' => $caldas->id],
            ['name' => 'Anserma', 'state_id' => $caldas->id],
            ['name' => 'Aranzazu', 'state_id' => $caldas->id],
            ['name' => 'Belalcázar', 'state_id' => $caldas->id],
            ['name' => 'Chinchiná', 'state_id' => $caldas->id],
            ['name' => 'Filadelfia', 'state_id' => $caldas->id],
            ['name' => 'La Dorada', 'state_id' => $caldas->id],
            ['name' => 'La Merced', 'state_id' => $caldas->id],
            ['name' => 'Manzanares', 'state_id' => $caldas->id],
            ['name' => 'Marmato', 'state_id' => $caldas->id],
            ['name' => 'Marquetalia', 'state_id' => $caldas->id],
            ['name' => 'Marulanda', 'state_id' => $caldas->id],
            ['name' => 'Neira', 'state_id' => $caldas->id],
            ['name' => 'Norcasia', 'state_id' => $caldas->id],
            ['name' => 'Pácora', 'state_id' => $caldas->id],
            ['name' => 'Palestina', 'state_id' => $caldas->id],
            ['name' => 'Pensilvania', 'state_id' => $caldas->id],
            ['name' => 'Riosucio', 'state_id' => $caldas->id],
            ['name' => 'Risaralda', 'state_id' => $caldas->id],
            ['name' => 'Salamina', 'state_id' => $caldas->id],
            ['name' => 'Samaná', 'state_id' => $caldas->id],
            ['name' => 'San José', 'state_id' => $caldas->id],
            ['name' => 'Supía', 'state_id' => $caldas->id],
            ['name' => 'Victoria', 'state_id' => $caldas->id],
            ['name' => 'Villamaría', 'state_id' => $caldas->id],
            ['name' => 'Viterbo', 'state_id' => $caldas->id],

            //caqueta
            ['name' => 'Florencia', 'state_id' => $caqueta->id],
            ['name' => 'Albania', 'state_id' => $caqueta->id],
            ['name' => 'Belén de los Andaquíes', 'state_id' => $caqueta->id],
            ['name' => 'Cartagena del Chairá', 'state_id' => $caqueta->id],
            ['name' => 'Curillo', 'state_id' => $caqueta->id],
            ['name' => 'El Doncello', 'state_id' => $caqueta->id],
            ['name' => 'El Paujil', 'state_id' => $caqueta->id],
            ['name' => 'La Montañita', 'state_id' => $caqueta->id],
            ['name' => 'Milán', 'state_id' => $caqueta->id],
            ['name' => 'Morelia', 'state_id' => $caqueta->id],
            ['name' => 'Puerto Rico', 'state_id' => $caqueta->id],
            ['name' => 'San José del Fragua', 'state_id' => $caqueta->id],
            ['name' => 'San Vicente del Caguán', 'state_id' => $caqueta->id],
            ['name' => 'Solano', 'state_id' => $caqueta->id],
            ['name' => 'Solita', 'state_id' => $caqueta->id],
            ['name' => 'Valparaíso', 'state_id' => $caqueta->id],

            //casanare
            ['name' => 'Yopal', 'state_id' => $casanare->id],
            ['name' => 'Aguazul', 'state_id' => $casanare->id],
            ['name' => 'Chámeza', 'state_id' => $casanare->id],
            ['name' => 'Hato Corozal', 'state_id' => $casanare->id],
            ['name' => 'La Salina', 'state_id' => $casanare->id],
            ['name' => 'Maní', 'state_id' => $casanare->id],
            ['name' => 'Monterrey', 'state_id' => $casanare->id],
            ['name' => 'Nunchía', 'state_id' => $casanare->id],
            ['name' => 'Orocué', 'state_id' => $casanare->id],
            ['name' => 'Paz de Ariporo', 'state_id' => $casanare->id],
            ['name' => 'Pore', 'state_id' => $casanare->id],
            ['name' => 'Recetor', 'state_id' => $casanare->id],
            ['name' => 'Sabanalarga', 'state_id' => $casanare->id],
            ['name' => 'Sácama', 'state_id' => $casanare->id],
            ['name' => 'San Luis de Palenque', 'state_id' => $casanare->id],
            ['name' => 'Támara', 'state_id' => $casanare->id],
            ['name' => 'Tauramena', 'state_id' => $casanare->id],
            ['name' => 'Trinidad', 'state_id' => $casanare->id],
            ['name' => 'Villanueva', 'state_id' => $casanare->id],

            //cauca
            ['name' => 'Popayán', 'state_id' => $cauca->id],
            ['name' => 'Almaguer', 'state_id' => $cauca->id],
            ['name' => 'Argelia', 'state_id' => $cauca->id],
            ['name' => 'Balboa', 'state_id' => $cauca->id],
            ['name' => 'Bolívar', 'state_id' => $cauca->id],
            ['name' => 'Buenos Aires', 'state_id' => $cauca->id],
            ['name' => 'Cajibío', 'state_id' => $cauca->id],
            ['name' => 'Caldono', 'state_id' => $cauca->id],
            ['name' => 'Caloto', 'state_id' => $cauca->id],
            ['name' => 'Corinto', 'state_id' => $cauca->id],
            ['name' => 'El Tambo', 'state_id' => $cauca->id],
            ['name' => 'Florencia', 'state_id' => $cauca->id],
            ['name' => 'Guachené', 'state_id' => $cauca->id],
            ['name' => 'Guapí', 'state_id' => $cauca->id],
            ['name' => 'Inzá', 'state_id' => $cauca->id],
            ['name' => 'Jambaló', 'state_id' => $cauca->id],
            ['name' => 'La Sierra', 'state_id' => $cauca->id],
            ['name' => 'La Vega', 'state_id' => $cauca->id],
            ['name' => 'López de Micay', 'state_id' => $cauca->id],
            ['name' => 'Mercaderes', 'state_id' => $cauca->id],
            ['name' => 'Miranda', 'state_id' => $cauca->id],
            ['name' => 'Morales', 'state_id' => $cauca->id],
            ['name' => 'Padilla', 'state_id' => $cauca->id],
            ['name' => 'Páez', 'state_id' => $cauca->id],
            ['name' => 'Patía', 'state_id' => $cauca->id],
            ['name' => 'Piamonte', 'state_id' => $cauca->id],
            ['name' => 'Piendamó', 'state_id' => $cauca->id],
            ['name' => 'Puerto Tejada', 'state_id' => $cauca->id],
            ['name' => 'Puracé', 'state_id' => $cauca->id],
            ['name' => 'Rosas', 'state_id' => $cauca->id],
            ['name' => 'San Sebastián', 'state_id' => $cauca->id],
            ['name' => 'Santander de Quilichao', 'state_id' => $cauca->id],
            ['name' => 'Santa Rosa', 'state_id' => $cauca->id],
            ['name' => 'Silvia', 'state_id' => $cauca->id],
            ['name' => 'Sotará', 'state_id' => $cauca->id],
            ['name' => 'Suárez', 'state_id' => $cauca->id],
            ['name' => 'Sucre', 'state_id' => $cauca->id],
            ['name' => 'Timbío', 'state_id' => $cauca->id],
            ['name' => 'Timbiquí', 'state_id' => $cauca->id],
            ['name' => 'Toribio', 'state_id' => $cauca->id],
            ['name' => 'Totoró', 'state_id' => $cauca->id],
            ['name' => 'Villa Rica', 'state_id' => $cauca->id],

            //cesar
            ['name' => 'Valledupar', 'state_id' => $cesar->id],
            ['name' => 'Aguachica', 'state_id' => $cesar->id],
            ['name' => 'Agustín Codazzi', 'state_id' => $cesar->id],
            ['name' => 'Astrea', 'state_id' => $cesar->id],
            ['name' => 'Becerril', 'state_id' => $cesar->id],
            ['name' => 'Bosconia', 'state_id' => $cesar->id],
            ['name' => 'Chimichagua', 'state_id' => $cesar->id],
            ['name' => 'Chiriguaná', 'state_id' => $cesar->id],
            ['name' => 'Curumaní', 'state_id' => $cesar->id],
            ['name' => 'El Copey', 'state_id' => $cesar->id],
            ['name' => 'El Paso', 'state_id' => $cesar->id],
            ['name' => 'Gamarra', 'state_id' => $cesar->id],
            ['name' => 'González', 'state_id' => $cesar->id],
            ['name' => 'La Gloria', 'state_id' => $cesar->id],
            ['name' => 'La Jagua de Ibirico', 'state_id' => $cesar->id],
            ['name' => 'Manaure Balcón del Cesar', 'state_id' => $cesar->id],
            ['name' => 'Pailitas', 'state_id' => $cesar->id],
            ['name' => 'Pelaya', 'state_id' => $cesar->id],
            ['name' => 'Pueblo Bello', 'state_id' => $cesar->id],
            ['name' => 'Río de Oro', 'state_id' => $cesar->id],
            ['name' => 'La Paz', 'state_id' => $cesar->id],
            ['name' => 'San Alberto', 'state_id' => $cesar->id],
            ['name' => 'San Diego', 'state_id' => $cesar->id],
            ['name' => 'San Martín', 'state_id' => $cesar->id],
            ['name' => 'Tamalameque', 'state_id' => $cesar->id],

            //choco
            ['name' => 'Quibdó', 'state_id' => $choco->id],
            ['name' => 'Acandí', 'state_id' => $choco->id],
            ['name' => 'Alto Baudó', 'state_id' => $choco->id],
            ['name' => 'Atrato', 'state_id' => $choco->id],
            ['name' => 'Bagadó', 'state_id' => $choco->id],
            ['name' => 'Bahía Solano', 'state_id' => $choco->id],
            ['name' => 'Bajo Baudó', 'state_id' => $choco->id],
            ['name' => 'Bojayá', 'state_id' => $choco->id],
            ['name' => 'Cantón de San Pablo', 'state_id' => $choco->id],
            ['name' => 'Condoto', 'state_id' => $choco->id],
            ['name' => 'Cértegui', 'state_id' => $choco->id],
            ['name' => 'El Carmen de Atrato', 'state_id' => $choco->id],
            ['name' => 'El Carmen del Darién', 'state_id' => $choco->id],
            ['name' => 'El Litoral de San Juan', 'state_id' => $choco->id],
            ['name' => 'Istmina', 'state_id' => $choco->id],
            ['name' => 'Juradó', 'state_id' => $choco->id],
            ['name' => 'Lloró', 'state_id' => $choco->id],
            ['name' => 'Medio Atrato', 'state_id' => $choco->id],
            ['name' => 'Medio Baudó', 'state_id' => $choco->id],
            ['name' => 'Medio San Juan', 'state_id' => $choco->id],
            ['name' => 'Nóvita', 'state_id' => $choco->id],
            ['name' => 'Nuquí', 'state_id' => $choco->id],
            ['name' => 'Río Iró', 'state_id' => $choco->id],
            ['name' => 'Río Quito', 'state_id' => $choco->id],
            ['name' => 'Riosucio', 'state_id' => $choco->id],
            ['name' => 'San José del Palmar', 'state_id' => $choco->id],
            ['name' => 'Sipí', 'state_id' => $choco->id],
            ['name' => 'Tadó', 'state_id' => $choco->id],
            ['name' => 'Unguía', 'state_id' => $choco->id],
            ['name' => 'Unión Panamericana', 'state_id' => $choco->id],

            //cordoba
            ['name' => 'Montería', 'state_id' => $cordoba->id],
            ['name' => 'Ayapel', 'state_id' => $cordoba->id],
            ['name' => 'Buenavista', 'state_id' => $cordoba->id],
            ['name' => 'Canalete', 'state_id' => $cordoba->id],
            ['name' => 'Cereté', 'state_id' => $cordoba->id],
            ['name' => 'Chimá', 'state_id' => $cordoba->id],
            ['name' => 'Chinú', 'state_id' => $cordoba->id],
            ['name' => 'Ciénaga de Oro', 'state_id' => $cordoba->id],
            ['name' => 'Cotorra', 'state_id' => $cordoba->id],
            ['name' => 'La Apartada', 'state_id' => $cordoba->id],
            ['name' => 'Lorica', 'state_id' => $cordoba->id],
            ['name' => 'Los Córdobas', 'state_id' => $cordoba->id],
            ['name' => 'Momil', 'state_id' => $cordoba->id],
            ['name' => 'Montelíbano', 'state_id' => $cordoba->id],
            ['name' => 'Moñitos', 'state_id' => $cordoba->id],
            ['name' => 'Planeta Rica', 'state_id' => $cordoba->id],
            ['name' => 'Pueblo Nuevo', 'state_id' => $cordoba->id],
            ['name' => 'Puerto Escondido', 'state_id' => $cordoba->id],
            ['name' => 'Puerto Libertador', 'state_id' => $cordoba->id],
            ['name' => 'Purísima', 'state_id' => $cordoba->id],
            ['name' => 'Sahagún', 'state_id' => $cordoba->id],
            ['name' => 'San Andrés de Sotavento', 'state_id' => $cordoba->id],
            ['name' => 'San Antero', 'state_id' => $cordoba->id],
            ['name' => 'San Bernardo del Viento', 'state_id' => $cordoba->id],
            ['name' => 'San Carlos', 'state_id' => $cordoba->id],
            ['name' => 'San José de Uré', 'state_id' => $cordoba->id],
            ['name' => 'San Pelayo', 'state_id' => $cordoba->id],
            ['name' => 'Tierralta', 'state_id' => $cordoba->id],
            ['name' => 'Tuchín', 'state_id' => $cordoba->id],
            ['name' => 'Valencia', 'state_id' => $cordoba->id],
            
            // Cundinamarca
            ['name' => 'Agua de Dios', 'state_id' => $cundinamarca->id],
            ['name' => 'Albán', 'state_id' => $cundinamarca->id],
            ['name' => 'Anapoima', 'state_id' => $cundinamarca->id],
            ['name' => 'Anolaima', 'state_id' => $cundinamarca->id],
            ['name' => 'Apulo', 'state_id' => $cundinamarca->id],
            ['name' => 'Arbeláez', 'state_id' => $cundinamarca->id],
            ['name' => 'Beltrán', 'state_id' => $cundinamarca->id],
            ['name' => 'Bituima', 'state_id' => $cundinamarca->id],
            ['name' => 'Bojacá', 'state_id' => $cundinamarca->id],
            ['name' => 'Cabrera', 'state_id' => $cundinamarca->id],
            ['name' => 'Cachipay', 'state_id' => $cundinamarca->id],
            ['name' => 'Cajicá', 'state_id' => $cundinamarca->id],
            ['name' => 'Caparrapí', 'state_id' => $cundinamarca->id],
            ['name' => 'Cáqueza', 'state_id' => $cundinamarca->id],
            ['name' => 'Carmen de Carupa', 'state_id' => $cundinamarca->id],
            ['name' => 'Chaguaní', 'state_id' => $cundinamarca->id],
            ['name' => 'Chipaque', 'state_id' => $cundinamarca->id],
            ['name' => 'Choachí', 'state_id' => $cundinamarca->id],
            ['name' => 'Chocontá', 'state_id' => $cundinamarca->id],
            ['name' => 'Chía', 'state_id' => $cundinamarca->id],
            ['name' => 'Cogua', 'state_id' => $cundinamarca->id],
            ['name' => 'Cota', 'state_id' => $cundinamarca->id],
            ['name' => 'Cucunubá', 'state_id' => $cundinamarca->id],
            ['name' => 'El Colegio', 'state_id' => $cundinamarca->id],
            ['name' => 'El Peñón', 'state_id' => $cundinamarca->id],
            ['name' => 'El Rosal', 'state_id' => $cundinamarca->id],
            ['name' => 'Facatativá', 'state_id' => $cundinamarca->id],
            ['name' => 'Fómeque', 'state_id' => $cundinamarca->id],
            ['name' => 'Fosca', 'state_id' => $cundinamarca->id],
            ['name' => 'Funza', 'state_id' => $cundinamarca->id],
            ['name' => 'Fusagasugá', 'state_id' => $cundinamarca->id],
            ['name' => 'Fúquene', 'state_id' => $cundinamarca->id],
            ['name' => 'Gachalá', 'state_id' => $cundinamarca->id],
            ['name' => 'Gachancipá', 'state_id' => $cundinamarca->id],
            ['name' => 'Gachetá', 'state_id' => $cundinamarca->id],
            ['name' => 'Gama', 'state_id' => $cundinamarca->id],
            ['name' => 'Girardot', 'state_id' => $cundinamarca->id],
            ['name' => 'Granada', 'state_id' => $cundinamarca->id],
            ['name' => 'Guachetá', 'state_id' => $cundinamarca->id],
            ['name' => 'Guaduas', 'state_id' => $cundinamarca->id],
            ['name' => 'Guasca', 'state_id' => $cundinamarca->id],
            ['name' => 'Guataquí', 'state_id' => $cundinamarca->id],
            ['name' => 'Guatavita', 'state_id' => $cundinamarca->id],
            ['name' => 'Guayabal de Síquima', 'state_id' => $cundinamarca->id],
            ['name' => 'Guayabetal', 'state_id' => $cundinamarca->id],
            ['name' => 'Gutiérrez', 'state_id' => $cundinamarca->id],
            ['name' => 'Jerusalén', 'state_id' => $cundinamarca->id],
            ['name' => 'Junín', 'state_id' => $cundinamarca->id],
            ['name' => 'La Calera', 'state_id' => $cundinamarca->id],
            ['name' => 'La Mesa', 'state_id' => $cundinamarca->id],
            ['name' => 'La Palma', 'state_id' => $cundinamarca->id],
            ['name' => 'La Peña', 'state_id' => $cundinamarca->id],
            ['name' => 'La Vega', 'state_id' => $cundinamarca->id],
            ['name' => 'Lenguazaque', 'state_id' => $cundinamarca->id],
            ['name' => 'Machetá', 'state_id' => $cundinamarca->id],
            ['name' => 'Madrid', 'state_id' => $cundinamarca->id],
            ['name' => 'Manta', 'state_id' => $cundinamarca->id],
            ['name' => 'Medina', 'state_id' => $cundinamarca->id],
            ['name' => 'Mosquera', 'state_id' => $cundinamarca->id],
            ['name' => 'Nariño', 'state_id' => $cundinamarca->id],
            ['name' => 'Nemocón', 'state_id' => $cundinamarca->id],
            ['name' => 'Nilo', 'state_id' => $cundinamarca->id],
            ['name' => 'Nimaima', 'state_id' => $cundinamarca->id],
            ['name' => 'Nocaima', 'state_id' => $cundinamarca->id],
            ['name' => 'Pacho', 'state_id' => $cundinamarca->id],
            ['name' => 'Paime', 'state_id' => $cundinamarca->id],
            ['name' => 'Pandi', 'state_id' => $cundinamarca->id],
            ['name' => 'Paratebueno', 'state_id' => $cundinamarca->id],
            ['name' => 'Pasca', 'state_id' => $cundinamarca->id],
            ['name' => 'Puerto Salgar', 'state_id' => $cundinamarca->id],
            ['name' => 'Pulí', 'state_id' => $cundinamarca->id],
            ['name' => 'Quebradanegra', 'state_id' => $cundinamarca->id],
            ['name' => 'Quetame', 'state_id' => $cundinamarca->id],
            ['name' => 'Quipile', 'state_id' => $cundinamarca->id],
            ['name' => 'Ricaurte', 'state_id' => $cundinamarca->id],
            ['name' => 'San Antonio del Tequendama', 'state_id' => $cundinamarca->id],
            ['name' => 'San Bernardo', 'state_id' => $cundinamarca->id],
            ['name' => 'San Cayetano', 'state_id' => $cundinamarca->id],
            ['name' => 'San Francisco', 'state_id' => $cundinamarca->id],
            ['name' => 'San Juan de Rioseco', 'state_id' => $cundinamarca->id],
            ['name' => 'Sasaima', 'state_id' => $cundinamarca->id],
            ['name' => 'Sesquilé', 'state_id' => $cundinamarca->id],
            ['name' => 'Sibaté', 'state_id' => $cundinamarca->id],
            ['name' => 'Silvania', 'state_id' => $cundinamarca->id],
            ['name' => 'Simijaca', 'state_id' => $cundinamarca->id],
            ['name' => 'Soacha', 'state_id' => $cundinamarca->id],
            ['name' => 'Sopó', 'state_id' => $cundinamarca->id],
            ['name' => 'Subachoque', 'state_id' => $cundinamarca->id],
            ['name' => 'Suesca', 'state_id' => $cundinamarca->id],
            ['name' => 'Supatá', 'state_id' => $cundinamarca->id],
            ['name' => 'Susa', 'state_id' => $cundinamarca->id],
            ['name' => 'Sutatausa', 'state_id' => $cundinamarca->id],
            ['name' => 'Tausa', 'state_id' => $cundinamarca->id],
            ['name' => 'Tena', 'state_id' => $cundinamarca->id],
            ['name' => 'Tenjo', 'state_id' => $cundinamarca->id],
            ['name' => 'Tibacuy', 'state_id' => $cundinamarca->id],
            ['name' => 'Tibirita', 'state_id' => $cundinamarca->id],
            ['name' => 'Tocaima', 'state_id' => $cundinamarca->id],
            ['name' => 'Tocancipá', 'state_id' => $cundinamarca->id],
            ['name' => 'Topaipí', 'state_id' => $cundinamarca->id],
            ['name' => 'Ubalá', 'state_id' => $cundinamarca->id],
            ['name' => 'Ubaque', 'state_id' => $cundinamarca->id],
            ['name' => 'Ubaté', 'state_id' => $cundinamarca->id],
            ['name' => 'Une', 'state_id' => $cundinamarca->id],
            ['name' => 'Útica', 'state_id' => $cundinamarca->id],
            ['name' => 'Venecia', 'state_id' => $cundinamarca->id],
            ['name' => 'Vergara', 'state_id' => $cundinamarca->id],
            ['name' => 'Vianí', 'state_id' => $cundinamarca->id],
            ['name' => 'Villagómez', 'state_id' => $cundinamarca->id],
            ['name' => 'Villapinzón', 'state_id' => $cundinamarca->id],
            ['name' => 'Villeta', 'state_id' => $cundinamarca->id],
            ['name' => 'Viotá', 'state_id' => $cundinamarca->id],
            ['name' => 'Yacopí', 'state_id' => $cundinamarca->id],
            ['name' => 'Zipacón', 'state_id' => $cundinamarca->id],
            ['name' => 'Zipaquirá', 'state_id' => $cundinamarca->id],

            //Guainia
            ['name' => 'Inírida', 'state_id' => $guainia->id],
            ['name' => 'Barranco Minas', 'state_id' => $guainia->id],

            //Guaviare
            ['name' => 'San José del Guaviare', 'state_id' => $guaviare->id],
            ['name' => 'Calamar', 'state_id' => $guaviare->id],
            ['name' => 'El Retorno', 'state_id' => $guaviare->id],
            ['name' => 'Miraflores', 'state_id' => $guaviare->id],

            //Huila
            ['name' => 'Neiva', 'state_id' => $huila->id],
            ['name' => 'Acevedo', 'state_id' => $huila->id],
            ['name' => 'Agrado', 'state_id' => $huila->id],
            ['name' => 'Aipe', 'state_id' => $huila->id],
            ['name' => 'Algeciras', 'state_id' => $huila->id],
            ['name' => 'Altamira', 'state_id' => $huila->id],
            ['name' => 'Baraya', 'state_id' => $huila->id],
            ['name' => 'Campoalegre', 'state_id' => $huila->id],
            ['name' => 'Colombia', 'state_id' => $huila->id],
            ['name' => 'Elías', 'state_id' => $huila->id],
            ['name' => 'Garzón', 'state_id' => $huila->id],
            ['name' => 'Gigante', 'state_id' => $huila->id],
            ['name' => 'Guadalupe', 'state_id' => $huila->id],
            ['name' => 'Hobo', 'state_id' => $huila->id],
            ['name' => 'Íquira', 'state_id' => $huila->id],
            ['name' => 'Isnos', 'state_id' => $huila->id],
            ['name' => 'La Argentina', 'state_id' => $huila->id],
            ['name' => 'La Plata', 'state_id' => $huila->id],
            ['name' => 'Nátaga', 'state_id' => $huila->id],
            ['name' => 'Oporapa', 'state_id' => $huila->id],
            ['name' => 'Paicol', 'state_id' => $huila->id],
            ['name' => 'Palermo', 'state_id' => $huila->id],
            ['name' => 'Palestina', 'state_id' => $huila->id],
            ['name' => 'Pital', 'state_id' => $huila->id],
            ['name' => 'Pitalito', 'state_id' => $huila->id],
            ['name' => 'Rivera', 'state_id' => $huila->id],
            ['name' => 'Saladoblanco', 'state_id' => $huila->id],
            ['name' => 'San Agustín', 'state_id' => $huila->id],
            ['name' => 'Santa María', 'state_id' => $huila->id],
            ['name' => 'Suaza', 'state_id' => $huila->id],
            ['name' => 'Tarqui', 'state_id' => $huila->id],
            ['name' => 'Tello', 'state_id' => $huila->id],
            ['name' => 'Teruel', 'state_id' => $huila->id],
            ['name' => 'Tesalia', 'state_id' => $huila->id],
            ['name' => 'Timaná', 'state_id' => $huila->id],
            ['name' => 'Villavieja', 'state_id' => $huila->id],
            ['name' => 'Yaguará', 'state_id' => $huila->id],

            //Guajira
            ['name' => 'Riohacha', 'state_id' => $guajira->id],
            ['name' => 'Albania', 'state_id' => $guajira->id],
            ['name' => 'Barrancas', 'state_id' => $guajira->id],
            ['name' => 'Dibulla', 'state_id' => $guajira->id],
            ['name' => 'Distracción', 'state_id' => $guajira->id],
            ['name' => 'El Molino', 'state_id' => $guajira->id],
            ['name' => 'Fonseca', 'state_id' => $guajira->id],
            ['name' => 'Hatonuevo', 'state_id' => $guajira->id],
            ['name' => 'La Jagua del Pilar', 'state_id' => $guajira->id],
            ['name' => 'Maicao', 'state_id' => $guajira->id],
            ['name' => 'Manaure', 'state_id' => $guajira->id],
            ['name' => 'San Juan del Cesar', 'state_id' => $guajira->id],
            ['name' => 'Uribia', 'state_id' => $guajira->id],
            ['name' => 'Urumita', 'state_id' => $guajira->id],
            ['name' => 'Villanueva', 'state_id' => $guajira->id],

            //Magdalena
            ['name' => 'Santa Marta', 'state_id' => $magdalena->id],
            ['name' => 'Algarrobo', 'state_id' => $magdalena->id],
            ['name' => 'Aracataca', 'state_id' => $magdalena->id],
            ['name' => 'Ariguaní', 'state_id' => $magdalena->id],
            ['name' => 'Cerro San Antonio', 'state_id' => $magdalena->id],
            ['name' => 'Chibolo', 'state_id' => $magdalena->id],
            ['name' => 'Ciénaga', 'state_id' => $magdalena->id],
            ['name' => 'Concordia', 'state_id' => $magdalena->id],
            ['name' => 'El Banco', 'state_id' => $magdalena->id],
            ['name' => 'El Piñón', 'state_id' => $magdalena->id],
            ['name' => 'El Retén', 'state_id' => $magdalena->id],
            ['name' => 'Fundación', 'state_id' => $magdalena->id],
            ['name' => 'Guamal', 'state_id' => $magdalena->id],
            ['name' => 'Nueva Granada', 'state_id' => $magdalena->id],
            ['name' => 'Pedraza', 'state_id' => $magdalena->id],
            ['name' => 'Pijiño del Carmen', 'state_id' => $magdalena->id],
            ['name' => 'Pivijay', 'state_id' => $magdalena->id],
            ['name' => 'Plato', 'state_id' => $magdalena->id],
            ['name' => 'Pueblo Viejo', 'state_id' => $magdalena->id],
            ['name' => 'Remolino', 'state_id' => $magdalena->id],
            ['name' => 'Sabanas de San Ángel', 'state_id' => $magdalena->id],
            ['name' => 'Salamina', 'state_id' => $magdalena->id],
            ['name' => 'San Sebastián de Buenavista', 'state_id' => $magdalena->id],
            ['name' => 'San Zenón', 'state_id' => $magdalena->id],
            ['name' => 'Santa Ana', 'state_id' => $magdalena->id],
            ['name' => 'Santa Bárbara de Pinto', 'state_id' => $magdalena->id],
            ['name' => 'Sitionuevo', 'state_id' => $magdalena->id],
            ['name' => 'Tenerife', 'state_id' => $magdalena->id],
            ['name' => 'Zapayán', 'state_id' => $magdalena->id],
            ['name' => 'Zona Bananera', 'state_id' => $magdalena->id],

            //Meta
            ['name' => 'Villavicencio', 'state_id' => $meta->id],
            ['name' => 'Acacías', 'state_id' => $meta->id],
            ['name' => 'Barranca de Upía', 'state_id' => $meta->id],
            ['name' => 'Cabuyaro', 'state_id' => $meta->id],
            ['name' => 'Castilla la Nueva', 'state_id' => $meta->id],
            ['name' => 'Cubarral', 'state_id' => $meta->id],
            ['name' => 'Cumaral', 'state_id' => $meta->id],
            ['name' => 'El Calvario', 'state_id' => $meta->id],
            ['name' => 'El Castillo', 'state_id' => $meta->id],
            ['name' => 'El Dorado', 'state_id' => $meta->id],
            ['name' => 'Fuente de Oro', 'state_id' => $meta->id],
            ['name' => 'Granada', 'state_id' => $meta->id],
            ['name' => 'Guamal', 'state_id' => $meta->id],
            ['name' => 'La Macarena', 'state_id' => $meta->id],
            ['name' => 'La Uribe', 'state_id' => $meta->id],
            ['name' => 'Lejanías', 'state_id' => $meta->id],
            ['name' => 'Mapiripán', 'state_id' => $meta->id],
            ['name' => 'Mesetas', 'state_id' => $meta->id],
            ['name' => 'Puerto Concordia', 'state_id' => $meta->id],
            ['name' => 'Puerto Gaitán', 'state_id' => $meta->id],
            ['name' => 'Puerto Lleras', 'state_id' => $meta->id],
            ['name' => 'Puerto López', 'state_id' => $meta->id],
            ['name' => 'Puerto Rico', 'state_id' => $meta->id],
            ['name' => 'Restrepo', 'state_id' => $meta->id],
            ['name' => 'San Carlos de Guaroa', 'state_id' => $meta->id],
            ['name' => 'San Juan de Arama', 'state_id' => $meta->id],
            ['name' => 'San Juanito', 'state_id' => $meta->id],
            ['name' => 'San Martín', 'state_id' => $meta->id],
            ['name' => 'Vista Hermosa', 'state_id' => $meta->id],

            //Nariño
            ['name' => 'Pasto', 'state_id' => $narino->id],
            ['name' => 'Albán', 'state_id' => $narino->id],
            ['name' => 'Aldana', 'state_id' => $narino->id],
            ['name' => 'Ancuya', 'state_id' => $narino->id],
            ['name' => 'Arboleda', 'state_id' => $narino->id],
            ['name' => 'Barbacoas', 'state_id' => $narino->id],
            ['name' => 'Belén', 'state_id' => $narino->id],
            ['name' => 'Buesaco', 'state_id' => $narino->id],
            ['name' => 'Chachagüí', 'state_id' => $narino->id],
            ['name' => 'Colón', 'state_id' => $narino->id],
            ['name' => 'Consacá', 'state_id' => $narino->id],
            ['name' => 'Contadero', 'state_id' => $narino->id],
            ['name' => 'Córdoba', 'state_id' => $narino->id],
            ['name' => 'Cuaspud', 'state_id' => $narino->id],
            ['name' => 'Cumbal', 'state_id' => $narino->id],
            ['name' => 'Cumbitara', 'state_id' => $narino->id],
            ['name' => 'El Charco', 'state_id' => $narino->id],
            ['name' => 'El Peñol', 'state_id' => $narino->id],
            ['name' => 'El Rosario', 'state_id' => $narino->id],
            ['name' => 'El Tablón de Gómez', 'state_id' => $narino->id],
            ['name' => 'El Tambo', 'state_id' => $narino->id],
            ['name' => 'Francisco Pizarro', 'state_id' => $narino->id],
            ['name' => 'Funes', 'state_id' => $narino->id],
            ['name' => 'Guachucal', 'state_id' => $narino->id],
            ['name' => 'Guaitarilla', 'state_id' => $narino->id],
            ['name' => 'Gualmatán', 'state_id' => $narino->id],
            ['name' => 'Iles', 'state_id' => $narino->id],
            ['name' => 'Imués', 'state_id' => $narino->id],
            ['name' => 'Ipiales', 'state_id' => $narino->id],
            ['name' => 'La Cruz', 'state_id' => $narino->id],
            ['name' => 'La Florida', 'state_id' => $narino->id],
            ['name' => 'La Llanada', 'state_id' => $narino->id],
            ['name' => 'La Tola', 'state_id' => $narino->id],
            ['name' => 'La Unión', 'state_id' => $narino->id],
            ['name' => 'Leiva', 'state_id' => $narino->id],
            ['name' => 'Linares', 'state_id' => $narino->id],
            ['name' => 'Los Andes', 'state_id' => $narino->id],
            ['name' => 'Magüí Payán', 'state_id' => $narino->id],
            ['name' => 'Mallama', 'state_id' => $narino->id],
            ['name' => 'Mosquera', 'state_id' => $narino->id],
            ['name' => 'Nariño', 'state_id' => $narino->id],
            ['name' => 'Olaya Herrera', 'state_id' => $narino->id],
            ['name' => 'Ospina', 'state_id' => $narino->id],
            ['name' => 'Policarpa', 'state_id' => $narino->id],
            ['name' => 'Potosí', 'state_id' => $narino->id],
            ['name' => 'Providencia', 'state_id' => $narino->id],
            ['name' => 'Puerres', 'state_id' => $narino->id],
            ['name' => 'Pupiales', 'state_id' => $narino->id],
            ['name' => 'Ricaurte', 'state_id' => $narino->id],
            ['name' => 'Roberto Payán', 'state_id' => $narino->id],
            ['name' => 'Samaniego', 'state_id' => $narino->id],
            ['name' => 'San Bernardo', 'state_id' => $narino->id],
            ['name' => 'San Lorenzo', 'state_id' => $narino->id],
            ['name' => 'San Pablo', 'state_id' => $narino->id],
            ['name' => 'San Pedro de Cartago', 'state_id' => $narino->id],
            ['name' => 'Sandoná', 'state_id' => $narino->id],
            ['name' => 'Santa Bárbara', 'state_id' => $narino->id],
            ['name' => 'Santacruz', 'state_id' => $narino->id],
            ['name' => 'Sapuyes', 'state_id' => $narino->id],
            ['name' => 'Tumaco', 'state_id' => $narino->id],

            //Norte santander
            ['name' => 'Cúcuta', 'state_id' => $nortesantander->id],
            ['name' => 'Ábrego', 'state_id' => $nortesantander->id],
            ['name' => 'Arboledas', 'state_id' => $nortesantander->id],
            ['name' => 'Bochalema', 'state_id' => $nortesantander->id],
            ['name' => 'Bucarasica', 'state_id' => $nortesantander->id],
            ['name' => 'Cácota', 'state_id' => $nortesantander->id],
            ['name' => 'Cáchira', 'state_id' => $nortesantander->id],
            ['name' => 'Chinácota', 'state_id' => $nortesantander->id],
            ['name' => 'Chitagá', 'state_id' => $nortesantander->id],
            ['name' => 'Convención', 'state_id' => $nortesantander->id],
            ['name' => 'Cucutilla', 'state_id' => $nortesantander->id],
            ['name' => 'Duranía', 'state_id' => $nortesantander->id],
            ['name' => 'El Carmen', 'state_id' => $nortesantander->id],
            ['name' => 'El Tarra', 'state_id' => $nortesantander->id],
            ['name' => 'El Zulia', 'state_id' => $nortesantander->id],
            ['name' => 'Gramalote', 'state_id' => $nortesantander->id],
            ['name' => 'Hacarí', 'state_id' => $nortesantander->id],
            ['name' => 'Herrán', 'state_id' => $nortesantander->id],
            ['name' => 'Labateca', 'state_id' => $nortesantander->id],
            ['name' => 'La Esperanza', 'state_id' => $nortesantander->id],
            ['name' => 'La Playa de Belén', 'state_id' => $nortesantander->id],
            ['name' => 'Los Patios', 'state_id' => $nortesantander->id],
            ['name' => 'Lourdes', 'state_id' => $nortesantander->id],
            ['name' => 'Mutiscua', 'state_id' => $nortesantander->id],
            ['name' => 'Ocaña', 'state_id' => $nortesantander->id],
            ['name' => 'Pamplona', 'state_id' => $nortesantander->id],
            ['name' => 'Pamplonita', 'state_id' => $nortesantander->id],
            ['name' => 'Puerto Santander', 'state_id' => $nortesantander->id],
            ['name' => 'Ragonvalia', 'state_id' => $nortesantander->id],
            ['name' => 'Salazar de Las Palmas', 'state_id' => $nortesantander->id],
            ['name' => 'San Calixto', 'state_id' => $nortesantander->id],
            ['name' => 'San Cayetano', 'state_id' => $nortesantander->id],
            ['name' => 'Santiago', 'state_id' => $nortesantander->id],
            ['name' => 'Sardinata', 'state_id' => $nortesantander->id],
            ['name' => 'Santo Domingo de Silos', 'state_id' => $nortesantander->id],
            ['name' => 'Teorama', 'state_id' => $nortesantander->id],
            ['name' => 'Tibú', 'state_id' => $nortesantander->id],
            ['name' => 'Toledo', 'state_id' => $nortesantander->id],
            ['name' => 'Villa Caro', 'state_id' => $nortesantander->id],
            ['name' => 'Villa del Rosario', 'state_id' => $nortesantander->id],

            //putumayo
            ['name' => 'Mocoa', 'state_id' => $putumayo->id],
            ['name' => 'Colón', 'state_id' => $putumayo->id],
            ['name' => 'Orito', 'state_id' => $putumayo->id],
            ['name' => 'Puerto Asís', 'state_id' => $putumayo->id],
            ['name' => 'Puerto Caicedo', 'state_id' => $putumayo->id],
            ['name' => 'Puerto Guzmán', 'state_id' => $putumayo->id],
            ['name' => 'Puerto Leguízamo', 'state_id' => $putumayo->id],
            ['name' => 'Sibundoy', 'state_id' => $putumayo->id],
            ['name' => 'San Francisco', 'state_id' => $putumayo->id],
            ['name' => 'San Miguel', 'state_id' => $putumayo->id],
            ['name' => 'Santiago', 'state_id' => $putumayo->id],
            ['name' => 'Valle del Guamuez', 'state_id' => $putumayo->id],
            ['name' => 'Villagarzón', 'state_id' => $putumayo->id],

            //quindio
            ['name' => 'Armenia', 'state_id' => $quindio->id],
            ['name' => 'Buenavista', 'state_id' => $quindio->id],
            ['name' => 'Calarcá', 'state_id' => $quindio->id],
            ['name' => 'Circasia', 'state_id' => $quindio->id],
            ['name' => 'Córdoba', 'state_id' => $quindio->id],
            ['name' => 'Filandia', 'state_id' => $quindio->id],
            ['name' => 'Génova', 'state_id' => $quindio->id],
            ['name' => 'La Tebaida', 'state_id' => $quindio->id],
            ['name' => 'Montenegro', 'state_id' => $quindio->id],
            ['name' => 'Pijao', 'state_id' => $quindio->id],
            ['name' => 'Quimbaya', 'state_id' => $quindio->id],
            ['name' => 'Salento', 'state_id' => $quindio->id],

            //risaralda
            ['name' => 'Pereira', 'state_id' => $risaralda->id],
            ['name' => 'Dosquebradas', 'state_id' => $risaralda->id],
            ['name' => 'Santa Rosa de Cabal', 'state_id' => $risaralda->id],
            ['name' => 'Marsella', 'state_id' => $risaralda->id],
            ['name' => 'La Virginia', 'state_id' => $risaralda->id],
            ['name' => 'Apía', 'state_id' => $risaralda->id],
            ['name' => 'Belén de Umbría', 'state_id' => $risaralda->id],
            ['name' => 'Balboa', 'state_id' => $risaralda->id],
            ['name' => 'Guática', 'state_id' => $risaralda->id],
            ['name' => 'La Celia', 'state_id' => $risaralda->id],
            ['name' => 'Quinchía', 'state_id' => $risaralda->id],
            ['name' => 'Santuario', 'state_id' => $risaralda->id],
            ['name' => 'Mistrató', 'state_id' => $risaralda->id],
            ['name' => 'Pueblo Rico', 'state_id' => $risaralda->id],

            //SanAndres
            ['name' => 'San Andrés', 'state_id' => $sanandres->id],
            ['name' => 'Providencia y Santa Catalina', 'state_id' => $sanandres->id],

            //Santander
            ['name' => 'Aguada', 'state_id' => $santander->id],
            ['name' => 'Albania', 'state_id' => $santander->id],
            ['name' => 'Aratoca', 'state_id' => $santander->id],
            ['name' => 'Barbosa', 'state_id' => $santander->id],
            ['name' => 'Barichara', 'state_id' => $santander->id],
            ['name' => 'Barrancabermeja', 'state_id' => $santander->id],
            ['name' => 'Betulia', 'state_id' => $santander->id],
            ['name' => 'Bolívar', 'state_id' => $santander->id],
            ['name' => 'Bucaramanga', 'state_id' => $santander->id],
            ['name' => 'Cabrera', 'state_id' => $santander->id],
            ['name' => 'California', 'state_id' => $santander->id],
            ['name' => 'Capitanejo', 'state_id' => $santander->id],
            ['name' => 'Carcasí', 'state_id' => $santander->id],
            ['name' => 'Cepitá', 'state_id' => $santander->id],
            ['name' => 'Cerrito', 'state_id' => $santander->id],
            ['name' => 'Charalá', 'state_id' => $santander->id],
            ['name' => 'Charta', 'state_id' => $santander->id],
            ['name' => 'Chima', 'state_id' => $santander->id],
            ['name' => 'Chipatá', 'state_id' => $santander->id],
            ['name' => 'Cimitarra', 'state_id' => $santander->id],
            ['name' => 'Concepción', 'state_id' => $santander->id],
            ['name' => 'Confines', 'state_id' => $santander->id],
            ['name' => 'Contratación', 'state_id' => $santander->id],
            ['name' => 'Coromoro', 'state_id' => $santander->id],
            ['name' => 'Curití', 'state_id' => $santander->id],
            ['name' => 'El Carmen de Chucurí', 'state_id' => $santander->id],
            ['name' => 'El Guacamayo', 'state_id' => $santander->id],
            ['name' => 'El Peñón', 'state_id' => $santander->id],
            ['name' => 'El Playón', 'state_id' => $santander->id],
            ['name' => 'Encino', 'state_id' => $santander->id],
            ['name' => 'Enciso', 'state_id' => $santander->id],
            ['name' => 'Florián', 'state_id' => $santander->id],
            ['name' => 'Floridablanca', 'state_id' => $santander->id],
            ['name' => 'Galán', 'state_id' => $santander->id],
            ['name' => 'Gámbita', 'state_id' => $santander->id],
            ['name' => 'Girón', 'state_id' => $santander->id],
            ['name' => 'Guaca', 'state_id' => $santander->id],
            ['name' => 'Guadalupe', 'state_id' => $santander->id],
            ['name' => 'Guapotá', 'state_id' => $santander->id],
            ['name' => 'Guavatá', 'state_id' => $santander->id],
            ['name' => 'Güepsa', 'state_id' => $santander->id],
            ['name' => 'Hato', 'state_id' => $santander->id],
            ['name' => 'Jesús María', 'state_id' => $santander->id],
            ['name' => 'Jordán', 'state_id' => $santander->id],
            ['name' => 'La Belleza', 'state_id' => $santander->id],
            ['name' => 'La Paz', 'state_id' => $santander->id],
            ['name' => 'Landázuri', 'state_id' => $santander->id],
            ['name' => 'Lebrija', 'state_id' => $santander->id],
            ['name' => 'Los Santos', 'state_id' => $santander->id],
            ['name' => 'Macaravita', 'state_id' => $santander->id],
            ['name' => 'Málaga', 'state_id' => $santander->id],
            ['name' => 'Matanza', 'state_id' => $santander->id],
            ['name' => 'Mogotes', 'state_id' => $santander->id],
            ['name' => 'Molagavita', 'state_id' => $santander->id],
            ['name' => 'Ocamonte', 'state_id' => $santander->id],
            ['name' => 'Oiba', 'state_id' => $santander->id],
            ['name' => 'Onzaga', 'state_id' => $santander->id],
            ['name' => 'Palmas del Socorro', 'state_id' => $santander->id],
            ['name' => 'Páramo', 'state_id' => $santander->id],
            ['name' => 'Piedecuesta', 'state_id' => $santander->id],
            ['name' => 'Pinchote', 'state_id' => $santander->id],
            ['name' => 'Puente Nacional', 'state_id' => $santander->id],
            ['name' => 'Puerto Parra', 'state_id' => $santander->id],
            ['name' => 'Puerto Wilches', 'state_id' => $santander->id],
            ['name' => 'Rionegro', 'state_id' => $santander->id],
            ['name' => 'Sabana de Torres', 'state_id' => $santander->id],
            ['name' => 'San Andrés', 'state_id' => $santander->id],
            ['name' => 'San Benito', 'state_id' => $santander->id],
            ['name' => 'San Gil', 'state_id' => $santander->id],
            ['name' => 'San Joaquín', 'state_id' => $santander->id],
            ['name' => 'San José de Miranda', 'state_id' => $santander->id],
            ['name' => 'San Miguel', 'state_id' => $santander->id],
            ['name' => 'San Vicente de Chucurí', 'state_id' => $santander->id],
            ['name' => 'Santa Bárbara', 'state_id' => $santander->id],
            ['name' => 'Santa Helena del Opón', 'state_id' => $santander->id],
            ['name' => 'Simacota', 'state_id' => $santander->id],
            ['name' => 'Socorro', 'state_id' => $santander->id],
            ['name' => 'Suaita', 'state_id' => $santander->id],
            ['name' => 'Sucre', 'state_id' => $santander->id],
            ['name' => 'Suratá', 'state_id' => $santander->id],
            ['name' => 'Tona', 'state_id' => $santander->id],
            ['name' => 'Valle de San José', 'state_id' => $santander->id],
            ['name' => 'Vélez', 'state_id' => $santander->id],
            ['name' => 'Vetas', 'state_id' => $santander->id],
            ['name' => 'Villanueva', 'state_id' => $santander->id],
            ['name' => 'Zapatoca', 'state_id' => $santander->id],

            //sucre
            ['name' => 'Sincelejo', 'state_id' => $sucre->id],
            ['name' => 'Buenavista', 'state_id' => $sucre->id],
            ['name' => 'Caimito', 'state_id' => $sucre->id],
            ['name' => 'Colosó', 'state_id' => $sucre->id],
            ['name' => 'Corozal', 'state_id' => $sucre->id],
            ['name' => 'Coveñas', 'state_id' => $sucre->id],
            ['name' => 'Chalán', 'state_id' => $sucre->id],
            ['name' => 'El Roble', 'state_id' => $sucre->id],
            ['name' => 'Galeras', 'state_id' => $sucre->id],
            ['name' => 'Guaranda', 'state_id' => $sucre->id],
            ['name' => 'La Unión', 'state_id' => $sucre->id],
            ['name' => 'Los Palmitos', 'state_id' => $sucre->id],
            ['name' => 'Majagual', 'state_id' => $sucre->id],
            ['name' => 'Morroa', 'state_id' => $sucre->id],
            ['name' => 'Ovejas', 'state_id' => $sucre->id],
            ['name' => 'Palmito', 'state_id' => $sucre->id],
            ['name' => 'Sampués', 'state_id' => $sucre->id],
            ['name' => 'San Benito Abad', 'state_id' => $sucre->id],
            ['name' => 'San Juan de Betulia', 'state_id' => $sucre->id],
            ['name' => 'San Marcos', 'state_id' => $sucre->id],
            ['name' => 'San Onofre', 'state_id' => $sucre->id],
            ['name' => 'San Pedro', 'state_id' => $sucre->id],
            ['name' => 'Sincé', 'state_id' => $sucre->id],
            ['name' => 'Sucre', 'state_id' => $sucre->id],
            ['name' => 'Tolú', 'state_id' => $sucre->id],
            ['name' => 'Tolúviejo', 'state_id' => $sucre->id],

            //Tolima
            ['name' => 'Ibagué', 'state_id' => $tolima->id],
            ['name' => 'Alpujarra', 'state_id' => $tolima->id],
            ['name' => 'Alvarado', 'state_id' => $tolima->id],
            ['name' => 'Ambalema', 'state_id' => $tolima->id],
            ['name' => 'Anzoátegui', 'state_id' => $tolima->id],
            ['name' => 'Armero Guayabal', 'state_id' => $tolima->id],
            ['name' => 'Ataco', 'state_id' => $tolima->id],
            ['name' => 'Cajamarca', 'state_id' => $tolima->id],
            ['name' => 'Carmen de Apicalá', 'state_id' => $tolima->id],
            ['name' => 'Casabianca', 'state_id' => $tolima->id],
            ['name' => 'Chaparral', 'state_id' => $tolima->id],
            ['name' => 'Coello', 'state_id' => $tolima->id],
            ['name' => 'Coyaima', 'state_id' => $tolima->id],
            ['name' => 'Cunday', 'state_id' => $tolima->id],
            ['name' => 'Dolores', 'state_id' => $tolima->id],
            ['name' => 'Espinal', 'state_id' => $tolima->id],
            ['name' => 'Falan', 'state_id' => $tolima->id],
            ['name' => 'Flandes', 'state_id' => $tolima->id],
            ['name' => 'Fresno', 'state_id' => $tolima->id],
            ['name' => 'Guamo', 'state_id' => $tolima->id],
            ['name' => 'Herveo', 'state_id' => $tolima->id],
            ['name' => 'Honda', 'state_id' => $tolima->id],
            ['name' => 'Icononzo', 'state_id' => $tolima->id],
            ['name' => 'Lérida', 'state_id' => $tolima->id],
            ['name' => 'Líbano', 'state_id' => $tolima->id],
            ['name' => 'Mariquita', 'state_id' => $tolima->id],
            ['name' => 'Melgar', 'state_id' => $tolima->id],
            ['name' => 'Murillo', 'state_id' => $tolima->id],
            ['name' => 'Natagaima', 'state_id' => $tolima->id],
            ['name' => 'Ortega', 'state_id' => $tolima->id],
            ['name' => 'Palocabildo', 'state_id' => $tolima->id],
            ['name' => 'Piedras', 'state_id' => $tolima->id],
            ['name' => 'Planadas', 'state_id' => $tolima->id],
            ['name' => 'Prado', 'state_id' => $tolima->id],
            ['name' => 'Purificación', 'state_id' => $tolima->id],
            ['name' => 'Rioblanco', 'state_id' => $tolima->id],
            ['name' => 'Roncesvalles', 'state_id' => $tolima->id],
            ['name' => 'Rovira', 'state_id' => $tolima->id],
            ['name' => 'Saldaña', 'state_id' => $tolima->id],
            ['name' => 'San Antonio', 'state_id' => $tolima->id],
            ['name' => 'San Luis', 'state_id' => $tolima->id],
            ['name' => 'Santa Isabel', 'state_id' => $tolima->id],
            ['name' => 'Suárez', 'state_id' => $tolima->id],
            ['name' => 'Valle de San Juan', 'state_id' => $tolima->id],
            ['name' => 'Venadillo', 'state_id' => $tolima->id],
            ['name' => 'Villahermosa', 'state_id' => $tolima->id],
            ['name' => 'Villarrica', 'state_id' => $tolima->id],

            // Valle del Cauca
            ['name' => 'Cali', 'state_id' => $valle->id],
            ['name' => 'Alcalá', 'state_id' => $valle->id],
            ['name' => 'Andalucía', 'state_id' => $valle->id],
            ['name' => 'Ansermanuevo', 'state_id' => $valle->id],
            ['name' => 'Argelia', 'state_id' => $valle->id],
            ['name' => 'Bolívar', 'state_id' => $valle->id],
            ['name' => 'Buenaventura', 'state_id' => $valle->id],
            ['name' => 'Buga', 'state_id' => $valle->id],
            ['name' => 'Bugalagrande', 'state_id' => $valle->id],
            ['name' => 'Caicedonia', 'state_id' => $valle->id],
            ['name' => 'Calima - El Darién', 'state_id' => $valle->id],
            ['name' => 'Candelaria', 'state_id' => $valle->id],
            ['name' => 'Cartago', 'state_id' => $valle->id],
            ['name' => 'Dagua', 'state_id' => $valle->id],
            ['name' => 'El Águila', 'state_id' => $valle->id],
            ['name' => 'El Cairo', 'state_id' => $valle->id],
            ['name' => 'El Cerrito', 'state_id' => $valle->id],
            ['name' => 'El Dovio', 'state_id' => $valle->id],
            ['name' => 'Florida', 'state_id' => $valle->id],
            ['name' => 'Ginebra', 'state_id' => $valle->id],
            ['name' => 'Guacarí', 'state_id' => $valle->id],
            ['name' => 'Jamundí', 'state_id' => $valle->id],
            ['name' => 'La Cumbre', 'state_id' => $valle->id],
            ['name' => 'La Unión', 'state_id' => $valle->id],
            ['name' => 'La Victoria', 'state_id' => $valle->id],
            ['name' => 'Obando', 'state_id' => $valle->id],
            ['name' => 'Palmira', 'state_id' => $valle->id],
            ['name' => 'Pradera', 'state_id' => $valle->id],
            ['name' => 'Restrepo', 'state_id' => $valle->id],
            ['name' => 'Riofrío', 'state_id' => $valle->id],
            ['name' => 'Roldanillo', 'state_id' => $valle->id],
            ['name' => 'San Pedro', 'state_id' => $valle->id],
            ['name' => 'Sevilla', 'state_id' => $valle->id],
            ['name' => 'Toro', 'state_id' => $valle->id],
            ['name' => 'Trujillo', 'state_id' => $valle->id],
            ['name' => 'Tuluá', 'state_id' => $valle->id],
            ['name' => 'Ulloa', 'state_id' => $valle->id],
            ['name' => 'Versalles', 'state_id' => $valle->id],
            ['name' => 'Vijes', 'state_id' => $valle->id],
            ['name' => 'Yotoco', 'state_id' => $valle->id],
            ['name' => 'Yumbo', 'state_id' => $valle->id],
            ['name' => 'Zarzal', 'state_id' => $valle->id],

            //Vaupes
            ['name' => 'Mitú', 'state_id' => $vaupes->id],
            ['name' => 'Carurú', 'state_id' => $vaupes->id],
            ['name' => 'Taraira', 'state_id' => $vaupes->id],

            //Vichada
            ['name' => 'Puerto Carreño', 'state_id' => $vichada->id],
            ['name' => 'La Primavera', 'state_id' => $vichada->id],
            ['name' => 'Santa Rosalía', 'state_id' => $vichada->id],
            ['name' => 'Cumaribo', 'state_id' => $vichada->id], 
        ]);
    }
}
